[package]
name = "java-env-manager"
version = "0.1.0"
authors = ["Tristan Partin <tristan.partin@gmail.com>"]

[dependencies]
clap = {version = "2.31", features = ["yaml"]}
libjem = {path = "../libjem"}
