image: tristan957/jem-ci:latest

cache:
  paths:
  - target/

stages:
  - build
  - test

build-cli:
  stage: build
  script:
    - cd $CI_PROJECT_PATH/java-env-manager-cli
    - cargo build
build-gui:
  stage: build
  script:
    - cd $CI_PROJECT_PATH/java-env-manager-gui
    - cargo build
