binop_separator = "Front"
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
brace_style = "SameLineWhere"
color = "Auto"
combine_control_expr = true
comment_width = 100
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
empty_item_single_line = true
error_on_line_overflow = true
error_on_unformatted = true
fn_args_density = "Tall"
fn_single_line = false
force_multiline_blocks = false
format_strings = true
hard_tabs = false
hide_parse_errors = false
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
match_arm_blocks = true
match_block_trailing_comma = true
max_width = 100
merge_derives = true
merge_imports = true
newline_style = "Unix"
normalize_comments = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
report_fixme = "Always"
report_todo = "Always"
# required_version = "CARGO_PKG_VERSION"
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 30
struct_lit_single_line = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = false
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = true
use_try_shorthand = true
where_single_line = false
wrap_comments = true
